Devsiteinfo:
    au_url: https://development.cottonon.com/AU/
    nz_url: https://development.cottonon.com/NZ/
    sa_url: https://development.cottonon.com/ZA/
    us_url: https://development.cottonon.com/US/
    my_url: https://development.cottonon.com/MY/
    sg_url: https://development.cottonon.com/SG/
    uk_url: https://development.typo.com/UK
    bm_url: https://dev04-ecom-cottonongroup.demandware.net/on/demandware.store/Sites-Site/default/ViewApplication-DisplayWelcomePage
    bm_username: lohit.kotian@cottonon.com.au
    bm_password: Cottonon1234%

  #base_url : https://development.cottonon.com
